default: &default
  redis_cache_store_url: redis://localhost:6379/1/cache
  redis_jobs_url: redis://localhost:6379/2/cache
  redis_asterisk_cache_store_url: redis://localhost:6379/3/cache

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default